### ISSUE TITLE
Updates? 

### ISSUE THREAD

**Issue by PrathamH** [YaroslavTER/2048#5]
First of all I like your project, the multi-player is working good.
For issues,
1. When both players are connected, one player taps the back button in bottom by mistake and taps play again to continue, his game doesn't continue, it is stuck on Connected 2/2.
2. I would want to play with all my friends at once but it seems only 2 players can be connected on a room? 
3. Any beginner's procedure to deploy server on heroku?

Hope you continue supporting this awesome project made by you! Couldn't find any other good multi-player 2048...

**Comment by YaroslavTER** [comment]
@PrathamH Hi, thanks. That's awesome that you like it, I appreciate that.

The first issue made on purpose, because if you connect to the existing room again it refreshes and all of the users lost their points.

Multiplayer made only for two players because the app is not popular. But if you want more users in the room, I can make it just write down how many users in the room do you want to be.

This video for me was helpful https://www.youtube.com/watch?v=MxfxiR8TVNU

**Comment by PrathamH** [comment]
@YaroslavTER Thanks for the reply, I think it would be great if there's no limit for multi-player considering we are using a server for it which can handle many users for this lite game I guess. The real time scores may be shown of just top 5 players or 10 and displaying full results at end of game for players.
It seems a lot competitive and fun! specially in this lock down period. 


Might be helpful for anyone seeing this out there, also found a good 2048 2 player offline version (for PC only)
here: https://github.com/316k/2048-2048
